// data.js

export const PRODUCTS = [
  { cod:'PN8317', name:'AMINO LIQ.2222 CEREJA-16 OZ. 1474 ML.', cat:'Proteinas' },
  { cod:'PN8332', name:'AMINO LIQ.2222 FRAMBOESA-16 OZ 474ML', cat:'Proteinas' },
  { cod:'PN8318', name:'AMINO LIQ.2222 FRUT. TROPICAIS 16 OZ/474ML', cat:'Proteinas' },
  { cod:'PN8319', name:'AMINO LIQ.2222 KIWI / MORANGO-16 OZ', cat:'Proteinas' },
  { cod:'PN8376', name:'AMINO LIQ.2222 PINK LIMONADE 160Z/474 ML', cat:'Proteinas' },
  { cod:'PN8320', name:'AMINO LIQ.2222 UVA-16 OZ.', cat:'Proteinas' },
  { cod:'PN8238', name:'AMINO LIQ.SCIENCE KIWI/MORANGO-16 OZ', cat:'Proteinas' },
  { cod:'PN8081', name:'AMINO SCIENCE BCAA POWDER F. TROPICAIS-600 GR', cat:'Aminoácidos' },
  { cod:'PN8168', name:'AMINO SCIENCE BCAA POWDER FRUTAS TROPICAIS 300 GR', cat:'Aminoácidos' },
  { cod:'PN8159', name:'AMINO SCIENCE BCAA POWDER LARANJA 300 GR', cat:'Aminoácidos' },
  { cod:'PN8079', name:'AMINO SCIENCE BCAA POWDER LARANJA-600 GR', cat:'Aminoácidos' },
  { cod:'PN8153', name:'AMINO SCIENCE BCAA POWDER LIMAO 300 GR', cat:'Aminoácidos' },
  { cod:'PN8080', name:'AMINO SCIENCE BCAA POWDER LIMAO-600 GR', cat:'Aminoácidos' },
  { cod:'PN8156', name:'AMINO SCIENCE BCAA POWDER MELANCIA 300 GR', cat:'Aminoácidos' },
  { cod:'PN8082', name:'AMINO SCIENCE BCAA POWDER MELANCIA-600 GR', cat:'Aminoácidos' },
  { cod:'PN8460', name:'ARGININE 150 GR', cat:'Aminoácidos' },
  { cod:'PN8054', name:'BCAA SCIENCE 1000-150 TABLETES', cat:'Aminoácidos' },
  { cod:'PN8176', name:'BCAA SCIENCE 2000-100 TABLETES', cat:'Aminoácidos' },
  { cod:'PN8170', name:'BCAA SCIENCE 500 COCO-200 TABLETES', cat:'Aminoácidos' },
  { cod:'PN8171', name:'BCAA SCIENCE 500 FRUTAS TROPICAIS-200 TABLETES', cat:'Aminoácidos' },
  { cod:'PN8174', name:'BCAA SCIENCE 500 LARANJA-200 TABLETES', cat:'Aminoácidos' },
  { cod:'PN8173', name:'BCAA SCIENCE 500 LIMAO-200 TABLETES', cat:'Aminoácidos' },
  { cod:'PN8326', name:'BCAA SCIENCE 500 PEPPERMINT-200 TABS', cat:'Aminoácidos' },
  { cod:'PN8001', name:'BETA SCIENCE-150GR', cat:'Aminoácidos' },
  { cod:'PN8131', name:'BIO CASEIN BAUNILHA 1,8 KG', cat:'Proteinas' },
  { cod:'PN8127', name:'BIO CASEIN BAUNILHA 909 GR', cat:'Proteinas' },
  { cod:'PN8132', name:'BIO CASEIN CHOCOLATE 1,8 KG', cat:'Proteinas' },
  { cod:'PN8128', name:'BIO CASEIN CHOCOLATE 909 GR', cat:'Proteinas' },
  { cod:'PN8365', name:"BIO CASEIN COOKIES'N CREAM-1,8KG", cat:'Proteinas' },
  { cod:'PN8363', name:"BIO CASEIN COOKIES'N CREAM-909 GR", cat:'Proteinas' },
  { cod:'PN8133', name:'BIO CASEIN MORANGO 1,8KG', cat:'Proteinas' },
  { cod:'PN8129', name:'BIO CASEIN MORANGO 909 GR', cat:'Proteinas' },
  { cod:'PN8305', name:'BIO COLLAGEN POWDER FRUTAS TROPICAIS-300 GR', cat:'Colágeno' },
  { cod:'PN8299', name:'BIO COLLAGEN POWDER LARANJA 300 GR', cat:'Colágeno' },
  { cod:'PN8297', name:'BIO COLLAGEN POWDER MORANGO 300 GR', cat:'Colágeno' },
  { cod:'PN8179', name:'BIO COLLAGEN POWDER SEM SABOR-300 GR', cat:'Colágeno' },
  { cod:'PN8298', name:'BIO COLLAGEN POWDER UVA 300 GR', cat:'Colágeno' },
  { cod:'PN8236', name:'BIO WHEY ISOPURO BANANA-909 GR', cat:'Proteinas' },
  { cod:'PN8016', name:'BIO WHEY ISOPURO BAUNILHA-909 GR', cat:'Proteinas' },
  { cod:'PN8017', name:'BIO WHEY ISOPURO CHOCOLATE BELGA-909 GR', cat:'Proteinas' },
  { cod:'PN8104', name:'BIO WHEY ISOPURO COCO-909 GR', cat:'Proteinas' },
  { cod:'PN8106', name:"BIO WHEY ISOPURO COOKIES'N CREAM 909 GR", cat:'Proteinas' },
  { cod:'PN8018', name:'BIO WHEY ISOPURO MORANGO-909 GR', cat:'Proteinas' },
  { cod:'PN8120', name:'BIO WHEY ISOPURO SEM SABOR-909 GR', cat:'Proteinas' },
  { cod:'PN8257', name:'BIO WHEY PROTEIN BANANA-1,8KG', cat:'Proteinas' },
  { cod:'PN8212', name:'BIO WHEY PROTEIN CHOCOLATE 1,8 KG', cat:'Proteinas' },
  { cod:'PN8107', name:"BIO WHEY PROTEIN COOKIES'N CREAM 1,8 KG", cat:'Proteinas' },
  { cod:'PN8213', name:'BIO WHEY PROTEIN MORANGO-1,8 KG', cat:'Proteinas' },
  { cod:'PN8211', name:'BIO WHEYPROTEIN BAUNILHA - 1,8 KG', cat:'Proteinas' },
  { cod:'PN8417', name:'CALCIUM CHELATED-100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8405', name:'CALCIUM MAGNEZIUM ZINC 100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8671', name:'CALCIUM MAGNEZIUM ZINC 30 CHELATED TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8399', name:'CHROMIUM PICOLINATE 100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8415', name:'COBRE CHELATED-100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8390', name:'COLLAGEN 600MG-100 CAPS', cat:'Colágeno' },
  { cod:'PN8672', name:'COLLAGEN 600MG-30 CAPS', cat:'Colágeno' },
  { cod:'PN8694', name:'COLLAGEN FRUTAS TROPICAIS 300 GR', cat:'Colágeno' },
  { cod:'PN8178', name:'COLLAGEN MASTIGAVEL LARANJA-150 TABLETES', cat:'Colágeno' },
  { cod:'PN8690', name:'COLLAGEN PEPTIDES BAUNILHA-320 GR', cat:'Colágeno' },
  { cod:'PN8692', name:'COLLAGEN PEPTIDES CAPPUCCINO-320 GR', cat:'Colágeno' },
  { cod:'PN8691', name:'COLLAGEN PEPTIDES CHOCOLATE 320gr', cat:'Colágeno' },
  { cod:'PN8703', name:'COLLAGEN PEPTIDES LARANJA-320 GR', cat:'Colágeno' },
  { cod:'PN8639', name:'COLLAGEN PEPTIDES MORANGO-320GR', cat:'Colágeno' },
  { cod:'PN8693', name:'COLLAGEN PEPTIDES SEM SABOR-320 GR', cat:'Colágeno' },
  { cod:'PN8638', name:'COLLAGEN PEPTIDES UVA-320GR', cat:'Colágeno' },
  { cod:'PN8302', name:'COQ 10/100 MG-30 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8303', name:'COQ 10-60 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'MKT0866', name:'COQUETEL.PP 650ML AZ CITAMPA SOBRE TAMPA AZ CIALCA', cat:'Coqueteleiras' },
  { cod:'PN8141', name:'CREA CHEWS MASTIGAVEL COCO-100 TABS', cat:'Aminoácidos' },
  { cod:'PN8143', name:'CREA CHEWS MASTIGAVEL LARANJA-100 TABS', cat:'Aminoácidos' },
  { cod:'PN8139', name:'CREA CHEWS MASTIGAVEL LIMAO-100 TABS', cat:'Aminoácidos' },
  { cod:'PN8147', name:'CREA CHEWS MASTIGAVEL MARACUJA-100 TABS', cat:'Aminoácidos' },
  { cod:'PN8140', name:'CREA CHEWS MASTIGAVEL PEPPERMINT-100 TABS', cat:'Aminoácidos' },
  { cod:'PN8145', name:'CREA CHEWS MASTIGAVEL PISTACHE-100 TABS', cat:'Aminoácidos' },
  { cod:'PN8142', name:'CREA CHEWS MASTIGAVEL UVA-100 TABS', cat:'Aminoácidos' },
  { cod:'PN8135', name:'CREA PEPTO SCIENCE 150 GR', cat:'Aminoácidos' },
  { cod:'PN8138', name:'CREA PEPTO SCIENCE 1KG', cat:'Aminoácidos' },
  { cod:'PN8136', name:'CREA PEPTO SCIENCE 300 GR', cat:'Aminoácidos' },
  { cod:'PN8137', name:'CREA PEPTO SCIENCE 600 GR', cat:'Aminoácidos' },
  { cod:'PN8612', name:'EVENING PRIMROSE OIL 500MG-100 SOFTS', cat:'Lipídios' },
  { cod:'PN8407', name:'FERRO CHELATED 100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8669', name:'FISH OIL OMEGA 3 1000MG 30 SOFTS', cat:'Lipídios' },
  { cod:'PN8002', name:'FISH OIL OMEGA 3 ULTRA PURO 600MG-90 CAPS', cat:'Lipídios' },
  { cod:'PN8613', name:'FLAXSEED OIL 600MG-100 SOFTS', cat:'Lipídios' },
  { cod:'PN8059', name:'FUN KOFFEE ENERGY CAFE EXPRESSO 250G', cat:'Energia e Bem-estar' },
  { cod:'PN8013', name:'FUN KOFFEE ENERGY CAPPUCCINO 250G', cat:'Energia e Bem-estar' },
  { cod:'PN8014', name:'FUN KOFFEE ENERGY CARAMEL MACCHIATO 250G', cat:'Energia e Bem-estar' },
  { cod:'PN8046', name:'GARLIC OIL 600MG-100 SOFTGEL', cat:'Lipídios' },
  { cod:'PN8023', name:'GLUCOSAMINA, CONDROITINA, MSM, UCIIE ACIDO HIALUR', cat:'Articulações' },
  { cod:'PN8055', name:'GLUTAMINA POWDER-150 GR', cat:'Aminoácidos' },
  { cod:'PN8058', name:'GLUTAMINA POWDER-1KG', cat:'Aminoácidos' },
  { cod:'PN8056', name:'GLUTAMINA POWDER-300 GR', cat:'Aminoácidos' },
  { cod:'PN8057', name:'GLUTAMINA POWDER-600 GR', cat:'Aminoácidos' },
  { cod:'PN8312', name:'GLYCO WAXY MAIZE SEM SABOR 2,0 KG', cat:'Carboidratos' },
  { cod:'PN8281', name:'GLYCOFUEL ENDURANCE FUEL FRUIT PUNCH 900GR', cat:'Carboidratos' },
  { cod:'PN8283', name:'GLYCOFUEL ENDURANCE FUEL GUARANA 909 GR', cat:'Carboidratos' },
  { cod:'PN8280', name:'GLYCOFUEL ENDURANCE FUEL LARANJA 909 GR', cat:'Carboidratos' },
  { cod:'PN8284', name:'GLYCOFUEL ENDURANCE FUEL LIMAO 909 GR', cat:'Carboidratos' },
  { cod:'PN8180', name:'GLYCOFUEL ENDURANCE FUEL PINK LEMONADE-909 GR', cat:'Carboidratos' },
  { cod:'PN8279', name:'GLYCOFUEL ENDURANCE FUEL UVA 909 GR', cat:'Carboidratos' },
  { cod:'PN8439', name:'GOURMET EXPRESSO COFFE WHEY CAFE LATTE-700 GR', cat:'Proteinas' },
  { cod:'PN8440', name:'GOURMET EXPRESSO COFFE WHEY CAPPUCCINO-700GR', cat:'Proteinas' },
  { cod:'PN8438', name:'GOURMET EXPRESSO COFFE WHEY MOCHA-700 GR', cat:'Proteinas' },
  { cod:'PN8459', name:'HMB-120 TABLETES', cat:'Aminoácidos' },
  { cod:'PN8688', name:'HYALURONIC ACID-60 TABLETES', cat:'Saúde e Bem-estar' },
  { cod:'PN8208', name:'ISO PALATINOSE-300 GR', cat:'Carboidratos' },
  { cod:'PN8353', name:'ISO PALATINOSE-600 GR', cat:'Carboidratos' },
  { cod:'PN8215', name:'ISO WHEY PROTEIN CHOCOLATE-2KG', cat:'Proteinas' },
  { cod:'PN8020', name:'ISO WHEY PROTEIN CHOCOLATE-909 GR', cat:'Proteinas' },
  { cod:'PN8216', name:'ISO WHEY PROTEIN MORANGO-2,273 GR', cat:'Proteinas' },
  { cod:'PN8026', name:'ISO WHEY PROTEIN MORANGO-909 GR', cat:'Proteinas' },
  { cod:'PN8214', name:'ISOLATE PERFORMANCE WHEY PROTEIN BAUNILHA-1,8KG', cat:'Proteinas' },
  { cod:'PN8360', name:"ISOLATE PERFORMANCE WHEY PROTEIN COOKIES 2 KG", cat:'Proteinas' },
  { cod:'PN8097', name:'ISOLATE PERFORMANCE WHEY PROTEIN SEM SABOR 909 GR', cat:'Proteinas' },
  { cod:'PN8642', name:'KETO FUEL 60 TABLETES', cat:'Lipídios' },
  { cod:'PN8437', name:'L-CARNERGY 2000 LIMAO-474 ML', cat:'Aminoácidos' },
  { cod:'PN8435', name:'L-CARNERGY 2000 TANGERINA-474 ML', cat:'Aminoácidos' },
  { cod:'PN8436', name:'L-CARNERGY 2000 UVA-474 ML', cat:'Aminoácidos' },
  { cod:'PN8227', name:'LEAN CAPS-90 SOFTGELS', cat:'Lipídios' },
  { cod:'PN8643', name:'LIFE GUARD 60 CAPSULAS', cat:'Lipídios' },
  { cod:'PN8401', name:'MAGNESIUM CHELATED-100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8670', name:'MAGNESIUM CHELATED-30 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8021', name:'MAGNESIUM MALATO-60 TABS', cat:'Vitaminas e Minerais' },
  { cod:'PN8022', name:'MAGNESIUM TAURATO 60 TABS', cat:'Vitaminas e Minerais' },
  { cod:'PN8411', name:'MANGANESE CHELATED-100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8201', name:'MCT SCIENCE POWDER-300 GR', cat:'Lipídios' },
  { cod:'PN8010', name:'MELATONINA-150 TABS', cat:'Saúde e Bem-estar' },
  { cod:'PN8346', name:'MIGHTY MASS 3000 BAUNILHA-3,0 KG', cat:'Carboidratos' },
  { cod:'PN8343', name:'MIGHTY MASS 3000 CHOCOLATE-3,0 KG', cat:'Carboidratos' },
  { cod:'PN8686', name:'MSM-60 TABLETES', cat:'Articulações' },
  { cod:'PN8182', name:'M-TOR MASTIGAVEL DOCE DE LEITE-150 TABLETES', cat:'Aminoácidos' },
  { cod:'PN8197', name:'MULTIPLEX MINERALS CHELATED-100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8011', name:'NAC-N-ACETYL CISTEINA 600MG 60 TABS', cat:'Aminoácidos' },
  { cod:'PN8689', name:'OSTEO TRI-FLEX-60 TABLETES', cat:'Articulações' },
  { cod:'PN8354', name:'PALATINOSE-1,0 KG', cat:'Carboidratos' },
  { cod:'PN8113', name:'PEPTO FUEL BAUNILHA 2 KG', cat:'Proteinas' },
  { cod:'PN8084', name:'PEPTO FUEL BAUNILHA 909 GR', cat:'Proteinas' },
  { cod:'PN8114', name:'PEPTO FUEL CHOCOLATE 2 KG', cat:'Proteinas' },
  { cod:'PN8078', name:'PEPTO FUEL CHOCOLATE 909 GR', cat:'Proteinas' },
  { cod:'PN8123', name:'PEPTO FUEL COCO-1,8KG', cat:'Proteinas' },
  { cod:'PN8122', name:'PEPTO FUEL COCO-909 GR', cat:'Proteinas' },
  { cod:'PN8362', name:"PEPTO FUEL COOKIES'N CREAM-1,8KG", cat:'Proteinas' },
  { cod:'PN8361', name:"PEPTO FUEL COOKIES'N CREAM-909 GR", cat:'Proteinas' },
  { cod:'PN8077', name:'PEPTO FUEL MORANGO 909 GR', cat:'Proteinas' },
  { cod:'PN8704', name:'PERFORM SIMPLY WHEY BAUNILHA 1,8 KG', cat:'Proteinas' },
  { cod:'PN8695', name:'PERFORM SIMPLY WHEY BAUNILHA 900 GR', cat:'Proteinas' },
  { cod:'PN8705', name:'PERFORM SIMPLY WHEY CHOCOLATE 1,8 KG', cat:'Proteinas' },
  { cod:'PN8696', name:'PERFORM SIMPLY WHEY CHOCOLATE 900 GR', cat:'Proteinas' },
  { cod:'PN8702', name:'PERFORM SIMPLY WHEY CHOCOLATE COCO 1,8 KG', cat:'Proteinas' },
  { cod:'PN8697', name:'PERFORM SIMPLY WHEY CHOCOLATE COCO 900 GR', cat:'Proteinas' },
  { cod:'PN8706', name:"PERFORM SIMPLY WHEY COOKIES'N CREAM 1,8 KG", cat:'Proteinas' },
  { cod:'PN8700', name:"PERFORM SIMPLY WHEY COOKIES'N CREAM 900 GR", cat:'Proteinas' },
  { cod:'PN8707', name:'PERFORM SIMPLY WHEY DOCE DE LEITE 1,8 KG', cat:'Proteinas' },
  { cod:'PN8701', name:'PERFORM SIMPLY WHEY DOCE DE LEITE 900 GR', cat:'Proteinas' },
  { cod:'PN8413', name:'POTASSIUM CHELATED-100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8092', name:'PURO PERFORMANCE WHEY BAUNILHA-909 GR', cat:'Whey Protein' },
  { cod:'PN8091', name:'PURO PERFORMANCE WHEY CHOCOLATE-909 GR', cat:'Whey Protein' },
  { cod:'PN8094', name:"PURO PERFORMANCE WHEY COOKIES'N CREAM-909 GR", cat:'Whey Protein' },
  { cod:'PN8093', name:'PURO PERFORMANCE WHEY MORANGO-909 GR', cat:'Whey Protein' },
  { cod:'PN8085', name:'PURO PERFORMANCE WHEY NATURAL-909 GR', cat:'Whey Protein' },
  { cod:'PN8685', name:'PURO WHEY BAUNILHA-1,8 KG', cat:'Whey Protein' },
  { cod:'PN8771', name:'PURO WHEY BAUNILHA-400 GR', cat:'Whey Protein' },
  { cod:'PN8456', name:'PURO WHEY CHOCOLATE MENTA 2KG', cat:'Whey Protein' },
  { cod:'PN8455', name:'PURO WHEY CHOCOLATE MENTA 909GR', cat:'Whey Protein' },
  { cod:'PN8683', name:'PURO WHEY CHOCOLATE-1,8 KG', cat:'Whey Protein' },
  { cod:'PN8770', name:'PURO WHEY CHOCOLATE-400 GR', cat:'Whey Protein' },
  { cod:'PN8682', name:"PURO WHEY COOKIES N CREAM-1,8 KG", cat:'Whey Protein' },
  { cod:'PN8773', name:"PURO WHEY COOKIES'N CREAM-400 GR", cat:'Whey Protein' },
  { cod:'PN8454', name:'PURO WHEY DOCE DE LEITE 1,8 KG', cat:'Whey Protein' },
  { cod:'PN8453', name:'PURO WHEY DOCE DE LEITE 909GR', cat:'Whey Protein' },
  { cod:'PN8458', name:'PURO WHEY FLORESTA NEGRA 2KG', cat:'Whey Protein' },
  { cod:'PN8457', name:'PURO WHEY FLORESTA NEGRA 909GR', cat:'Whey Protein' },
  { cod:'PN8684', name:'PURO WHEY MORANGO-1,8 KG', cat:'Whey Protein' },
  { cod:'PN8772', name:'PURO WHEY MORANGO-400 GR', cat:'Whey Protein' },
  { cod:'PN8434', name:'PURO WHEY NATURAL - 1,8 KG', cat:'Whey Protein' },
  { cod:'PN8443', name:'PURO WHEY PISTACHE 1,8KG', cat:'Whey Protein' },
  { cod:'PN8442', name:'PURO WHEY PISTACHE 909G', cat:'Whey Protein' },
  { cod:'PN8774', name:'PURO WHEY SEM SABOR-400 GR', cat:'Whey Protein' },
  { cod:'PN8452', name:'PURO WHEY TORTA DE LIMAO 2KG', cat:'Whey Protein' },
  { cod:'PN8451', name:'PURO WHEY TORTA DE LIMAO 909GR', cat:'Whey Protein' },
  { cod:'PN8146', name:'RECOVER ENDURANCE FUEL LIMAO 1KG', cat:'Carboidratos' },
  { cod:'PN8150', name:'RECOVER ENDURANCE FUEL TANGERINA 1KG', cat:'Carboidratos' },
  { cod:'PN8385', name:'RIBOSE ENERGY-300 GR', cat:'Carboidratos' },
  { cod:'PN8409', name:'SELENIUM CHELATED 100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8370', name:"SERIOUS GAINER COOKIES'N CREAM-3,0 KG", cat:'Carboidratos' },
  { cod:'PN8225', name:'SERIOUS PERF.GAINER BAUNILHA-3,0 KG', cat:'Carboidratos' },
  { cod:'PN8224', name:'SERIOUS PERF.GAINER CHOCOLATE-3,0 KG', cat:'Carboidratos' },
  { cod:'PN8226', name:'SERIOUS PERF.GAINER MORANGO-3,0 KG', cat:'Carboidratos' },
  { cod:'PN8313', name:'SHRED THERMAX-90 TABLETES', cat:'Termogênicos' },
  { cod:'PN8391', name:'SPIKE CAFEINE 105 MG-120 TABLETES', cat:'Termogênicos' },
  { cod:'PN8680', name:"SYNTHESYS EAA'S BOX 30 UNID. DOSE UNICA-FR. TROP", cat:'Aminoácidos' },
  { cod:'PN8681', name:"SYNTHESYS EAA'S BOX 30 UNID. DOSE UNICA-LARANJA", cat:'Aminoácidos' },
  { cod:'PN8679', name:"SYNTHESYS EAA'S BOX 30 UNID. DOSE UNICA-LIMAO", cat:'Aminoácidos' },
  { cod:'PN8473', name:'TAURINE 150 GR', cat:'Aminoácidos' },
  { cod:'PN8655', name:'THE CLASH PRE PERF WORKOUT CAR.MOCCHIATO 500 GR', cat:'Pré-treino' },
  { cod:'PN8656', name:'THE CLASH PRE PERF.WORKOUT CAFE TWIST 500GR', cat:'Pré-treino' },
  { cod:'PN8654', name:'THE CLASH PRE WORKOUT FRAMBOESA 500GR', cat:'Pré-treino' },
  { cod:'PN8651', name:'THE CLASH PRE WORKOUT FRUTAS TROPICAIS 500GR', cat:'Pré-treino' },
  { cod:'PN8653', name:'THE CLASH PRE WORKOUT GUARANA 500GR', cat:'Pré-treino' },
  { cod:'PN8652', name:'THE CLASH PRE WORKOUT MELANCIA 500GR', cat:'Pré-treino' },
  { cod:'PN8687', name:'UC-II-60 TABLETES', cat:'Articulações' },
  { cod:'PN8480', name:'ULTRA OMEGA TG 750 60 CAPS', cat:'Lipídios' },
  { cod:'PN8761', name:'ULTRUM COQ 10-100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8760', name:'ULTRUM COQ 10-60 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8199', name:'ULTRUM MULTIVITAM MINERAL-100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8389', name:'ULTRUM MULTIVITAM MINERAL-30 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8388', name:'ULTRUM MULTIVITAM MINERAL-60 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8699', name:'VERY JOY DOCE DE LEITE-60 TABS (MASTIGAVEL)', cat:'Colágeno' },
  { cod:'PN8698', name:'VERY JOY UVA-60 TABS (MASTIGAVEL)', cat:'Colágeno' },
  { cod:'PN8756', name:'VIT C 1000 D3 2000UI 60 TABS', cat:'Vitaminas e Minerais' },
  { cod:'PN8755', name:'VIT C 1000 ZINC 29MG 60 TABS', cat:'Vitaminas e Minerais' },
  { cod:'PN8757', name:'VIT C 1000D3 2000UI ZINC 29MG 60 TABS', cat:'Vitaminas e Minerais' },
  { cod:'PN8486', name:'VITAMINA C 1000 MG 100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8666', name:'VITAMINA C 1000 MG 30 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8485', name:'VITAMINA C 1000 MG 60 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8488', name:'VITAMINA C 1500 MG 60 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8484', name:'VITAMINA C 500 MG 100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8483', name:'VITAMINA C 500 MG 60 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8581', name:'VITAMINA C 500MG 30 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8753', name:'VITAMINA D3 100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8494', name:'VITAMINA D3 2000 UI-100 CAPSULAS', cat:'Vitaminas e Minerais' },
  { cod:'PN8667', name:'VITAMINA D3 2000 UI-30 CAPSULAS', cat:'Vitaminas e Minerais' },
  { cod:'PN8640', name:'VITAPLEX-100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8403', name:'ZINC CHELATED-100 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8441', name:'ZINC CHELATED-30 TABLETES', cat:'Vitaminas e Minerais' },
  { cod:'PN8118', name:'ZMAX MIDNIGHT 100 TABS', cat:'Vitaminas e Minerais' },
];

export const PRODUCT_CATS = [...new Set(PRODUCTS.map(p=>p.cat))].sort();

export const CATEGORIES = {
  URGENCIA:      { label:"URGÊNCIA",       color:"#EF4444", bg:"#FEF2F2", dot:"#EF4444" },
  OPERACAO:      { label:"OPERAÇÃO",       color:"#F97316", bg:"#FFF7ED", dot:"#F97316" },
  ADMINISTRATIVO:{ label:"ADMINISTRATIVO", color:"#3B82F6", bg:"#EFF6FF", dot:"#3B82F6" },
  DEGUSTACAO:    { label:"DEGUSTAÇÃO",     color:"#8B5CF6", bg:"#F5F3FF", dot:"#8B5CF6" },
  PRIORIDADE:    { label:"PRIORIDADE",     color:"#10B981", bg:"#ECFDF5", dot:"#10B981" },
  LEMBRETE:      { label:"LEMBRETE",       color:"#F59E0B", bg:"#FFFBEB", dot:"#F59E0B" },
};

export const SELLER_ACTIONS = [
  { key:"status",   label:"Status de Pedido",  icon:"📋", cat:"ADMINISTRATIVO" },
  { key:"cnpj",     label:"Troca de CNPJ",     icon:"🏢", cat:"ADMINISTRATIVO" },
  { key:"endereco", label:"Troca de Endereço", icon:"📍", cat:"ADMINISTRATIVO" },
  { key:"boleto",   label:"Boletos",           icon:"💳", cat:"ADMINISTRATIVO" },
  { key:"dev",      label:"Devoluções",        icon:"↩️",  cat:"URGENCIA" },
];

export const INITIAL_SELLERS = ["Luiz Penha","Alessandro","Matheus Maurer","Diego Duque","Luciano","Nicolau Salomon"];

export const INITIAL_RONALDO = [
  { id:101, cnpj:"12.345.678/0001-99", ref:"Pedido #3089", date:"2026-06-25", status:"Em aberto" },
  { id:102, cnpj:"98.765.432/0001-11", ref:"Pedido #3090", date:"2026-06-20", status:"Concluído" },
  { id:103, cnpj:"55.444.333/0001-22", ref:"NF #1821",     date:"2026-06-15", status:"Atrasado" },
];

export const INITIAL_ACTIONS = {
  "2026-06-29": [
    { id:1, cat:"URGENCIA",       title:"Resolver Erro de Boleto",           seller:"Nicolau Salomon", note:"NF #44210",               reminder:"", done:false },
    { id:2, cat:"OPERACAO",       title:"Validar Documentação de Exportação", seller:"",               note:"",                         reminder:"09:00", done:false },
    { id:3, cat:"ADMINISTRATIVO", title:"Troca de Endereço no Sistema",       seller:"Diego Duque",    note:"CNPJ 12.345.678/0001-99",  reminder:"", done:false },
    { id:4, cat:"DEGUSTACAO",     title:"Evento 15h — Cliente VIP",           seller:"",               note:"",                         reminder:"14:30", done:false },
  ],
  "2026-06-30": [
    { id:6, cat:"PRIORIDADE", title:"Acompanhar pedido exportação #4421", seller:"", note:"", reminder:"08:00", done:false },
    { id:7, cat:"OPERACAO",   title:"Terceirização: revisão de contrato",  seller:"", note:"", reminder:"", done:false },
  ],
};
